name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/s4lauth:latest ./Auth/
          docker build -t ${{ secrets.DOCKER_USERNAME }}/s4lgame:latest ./Game/
          docker push ${{ secrets.DOCKER_USERNAME }}/s4lauth:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/s4lgame:latest

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy docker-compose.yml to VPS
        run: |
          scp -o StrictHostKeyChecking=no -P ${{ secrets.SSH_PORT }} docker-compose.yml ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/home/dera.abdul/docker-compose.yml

      - name: Pulling Image
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
            docker stop s4lauth || true
            docker rm s4lauth || true
            docker stop s4lgame || true
            docker rm s4lgame || true
            docker rmi ${{ secrets.DOCKER_USERNAME }}/s4lauth:latest || true
            docker rmi ${{ secrets.DOCKER_USERNAME }}/s4lgame:latest || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/s4lauth:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/s4lgame:latest
          EOF

      - name: Create .env file on server
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
            echo "DB_HOST=${{ secrets.DB_HOST }}" > /home/dera.abdul/.env
            echo "DB_PORT=${{ secrets.DB_PORT }}" >> /home/dera.abdul/.env
            echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> /home/dera.abdul/.env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> /home/dera.abdul/.env
            echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> /home/dera.abdul/.env
            echo "API_AUTH=${{ secrets.API_AUTH }}" >> /home/dera.abdul/.env
            echo "API_GAME=${{ secrets.API_GAME }}" >> /home/dera.abdul/.env
            echo "IP_SERVER=${{ secrets.IP_SERVER }}" >> /home/dera.abdul/.env
          EOF

      - name: Deploying
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
            # Load environment variables from .env
            set -o allexport; source /home/dera.abdul/.env; set +o allexport

            # Run Docker Compose
            docker-compose -f /home/dera.abdul/docker-compose.yml up -d
          EOF
